#!/bin/bash

# week2-check-3

# Author:  Murray Saul
# Date:    January 8, 2020
# Modified by:	Jason Carman
# Modified:	May 16, 2023
#
# Purpose: Check that user correctly manipulated the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]
 then
  echo -e "\033[1mERROR:\033[0m"
  echo
  echo "You are NOT located in your HOME directory."
  echo -e "(i.e. \033[1m$HOME\033[0m )"
  echo
  echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
  echo -e "and confirm that you are"
  echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
  echo "and re-run this checking script."
  echo
  echo

  exit 1
fi


# Start checking week2 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory cnet204/notes removed in home directory
echo -n "Checking \"cnet204/notes\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet204/notes" "The directory pathname \"$HOME/cnet204/notes\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet204/notes\" in your home directory and re-run this checking script"

# Check directory cnet204/tutorials removed in home directory
echo -n "Checking \"cnet204/tutorials\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet204/tutorials" "The directory pathname \"$HOME/cnet204/tutorials\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet204/tutorials\" in your home directory and re-run this checking script"

# Check directory cnet204/samples removed in home directory
echo -n "Checking \"cnet204/samples\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet204/samples" "The directory pathname \"$HOME/cnet204/samples\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet204/samples\" in your home directory and re-run this checking script"

# Check directory cnet124 created in removed directory
echo -n "Checking \"cnet124\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet124" "The directory pathname \"$HOME/cnet124\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet124\" in your home directory and re-run this checking script"

# Check directory cnet124/cnet204 removed in home directory
echo -n "Checking \"cnet124/cnet204\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet124/cnet204" "The directory pathname \"$HOME/cnet124/cnet204\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet124/cnet204\" in your home directory and re-run this checking script"

# Check directory cnet124/cnet204/notes removed in home directory
echo -n "Checking \"cnet124/cnet204/notes\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet124/cnet204/notes" "The directory pathname \"$HOME/cnet124/cnet204/notes\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet124/cnet204/notes\" in your home directory and re-run this checking script"

# Check directory cnet124/cnet204/tutorials removed in home directory
echo -n "Checking \"cnet124/cnet204/tutorials\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet124/cnet204/tutorials" "The directory pathname \"$HOME/cnet124/cnet204/tutorials\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet124/cnet204/tutorials\" in your home directory and re-run this checking script"

# Check directory cnet124/cnet204/samples removed in home directory
echo -n "Checking \"cnet124/cnet204/samples\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet124/cnet204/samples" "The directory pathname \"$HOME/cnet124/cnet204/samples\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet124/cnet204/samples\" in your home directory and re-run this checking script"

# Check directory cnet124/cnet204/tutorials/cnet104 removed in home directory
echo -n "Checking \"cnet124/cnet204/tutorials/cnet104\" directory has been removed in your home directory: "
check "! test -d $HOME/cnet124/cnet204/tutorials/cnet104" "The directory pathname \"$HOME/cnet124/cnet204/tutorials/cnet104\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"cnet124/cnet204/tutorials/cnet104\" in your home directory and re-run this checking script"
